### ISSUE TITLE
Cannot initiate or respond to off-realm whispers

### ISSUE THREAD

**Issue by Martypedia** [Legacy-of-Sylvanaar/wow-instant-messenger#76]
Ever since 10.2.7 hit, whispering people on another server stopped working. I can _receive_ whispers just fine, but I cannot respond or initiate; I always get the error message that the recipient does not exist.

Issue is only present for character whispers, bnet communication works just fine.

**Comment by Yuraky** [comment]
There is a problem, namely someone writes in the /Trade of the server Mal'ganis, the server is not inserted in the WIM window with so coincidence Mal'ganis, Wim tries to whisper coincidence, which of course does not exist on the server Blackhand, then this is very annoying because when people try to write to players from Mal'ganis they get the message "coincidence" is not online.

**Comment by Pazza** [comment]
@Yuraky does that happen to every server user or just Mal'ganis? I wonder if its something as simple as an expression update that isn't accounting for the apostrophe in the server name.

**Comment by Martypedia** [comment]
I can supplement that this (still) happens to whispers going off-server - single word, apostrophe or two words.

**Comment by Pazza** [comment]
Thank you for the details.

**Comment by kirothius** [comment]
I'm on the french server "confrérie du thorium" and it doesn't work too

**Comment by kirothius** [comment]
and it works when whispering a player on the same server as mine.
